name: update_device_id
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  google_fonts: ^7.0.2
  installed_apps: ^2.1.0
  root_plus: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/logo.png
    - assets/logo_foreground.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#0F1114"
  adaptive_icon_foreground: "assets/logo_foreground.png"
  remove_alpha_ios: true
